---
- include_tasks: git.yaml
- name: Install prerequisites to add a new cert
  become: yes
  apt:
    state: present
    pkg:
        - gnupg2 
        - software-properties-common 
        - apt-transport-https 
        - curl

- name: install key (apt)
  become: yes
  apt_key:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    state: present


- name: Add vscode repository into sources list
  become: yes
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present

- name: Install VSCode
  become: yes
  apt:
    pkg:
        - code
    state: present

- name: Install tmux
  become: yes
  apt:
    state: present
    pkg:
        - tmux

- name: Install jq
  become: yes
  apt:
    state: present
    pkg:
        - jq

- name: Install npm and node
  become: yes
  apt:
    state: present
    pkg:
        - nodejs
        - npm

- name: Install vue via npm globally
  become: yes
  community.general.npm:
    name: '@vue/cli'
    global: true
