---
- include_tasks: spotify.yaml
- name: Install redshift
  become: yes
  ansible.builtin.apt:
    name: redshift-gtk
    state: present

- name: Copy redshift conf
  become: no
  copy:
    src: redshift.conf
    dest: "~/.config/redshift.conf"
    backup: yes
    mode: 0640

- name: Install chrome
  become: yes
  ansible.builtin.apt:
    name: google-chrome-stable
    state: present
