---
- name: spotify |no apt key
  become: yes
  ansible.builtin.get_url:
    url: https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg
    dest: /etc/apt/trusted.gpg.d/spotify.asc

- name: spotify | apt source
  become: yes
  ansible.builtin.apt_repository:
      repo: "deb http://repository.spotify.com stable non-free"
      state: present

- name: Install spotify
  become: yes
  ansible.builtin.apt:
    name: spotify-client
    state: present
    update_cache: yes
